### ISSUE TITLE
oauth2client.getToken() returns Error: redirect_uri_mismatch

### ISSUE THREAD

**Issue by minqi** [google/google-api-nodejs-client#744]
I am implementing the standard authorization code grant flow using the OAuth2 object. I am able to construct the authentication URL, and my redirect URL is getting called with the code={auth_token} once authentication is successful. However, when I try to exchange the code for the access token using the function "getToken(code, callback)," I receive the error 
```
Error: redirect_uri_mismatch
    at Request._callback (/Users/me/projects/dash/node_modules/google-auth-library/lib/transporters.js:81:15)
    at Request.self.callback (/Users/me/projects/dash/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/Users/me/projects/dash/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (/Users/me/projects/dash/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20) code: 400 }
```

In the credentials view of the Developer Console, I have registered callbacks for 
```
http://localhost:4444/oauthcallback
http://localhost:4444/oauthcallback/
```
I am not sure why getToken should even care about the redirect, as I am expecting it to just return the accessToken data on success. This seems to be a bug in the api client.

**Comment by minqi** [comment]
SOLVED: The issue was that when I passed the generated auth URL to a meta tag in my html header, Nunjucks was appending a trailing '/' to the URL, which Google's server interpreted as being part of the redirect_uri value (as this param was the last URL param in sequence). I fixed by cleaning the auth URL of any trailing '/' via
```
oauthurl.replace(/\/$/, '')
```

**Comment by tanwar1998** [comment]
You are right to explain it, but it is not still working as the trailing '/' is yet not removed. It is still showing on the google error page.
